apiVersion: v1
kind: Service
metadata:
  labels:
    app: customtaskservice
  name: customtaskservice
spec:
  ports:
    - name: "8110"
      port: 8110
      targetPort: 8110
  selector:
    app: customtaskservice